#!/bin/bash

myhome=/home/user
lastdate=$(find /home/user/ -name "Backup*" | awk 'BEGIN{FS="-"; OFS="-"}{print $2,$3,$4}' | sort -n | tail -1)
lastdatedir=$myhome/Backup-${lastdate}


if [[ -z "$lastdate" ]]; then
	exit
fi

if [[ -d $myhome/restore ]]; then
	rm -r $myhome/restore
fi

mkdir $myhome/restore

for filesource in $(ls $lastdatedir | grep -E -v "\.[0-9]{4}-[0-9]{2}-[0-9]{2}$"); do
	cp "${lastdatedir}/${filesource}" "$myhome/restore/${filesource}"
done
